kraken_admin_homepage:
    locales:  { en: "/admin/dashboard", fr: "/admin/accueil"}
    defaults: { _controller: KrakenAdminBundle:Dashboard:index }

#Scenario models

kraken_admin_scenario:
    locales:  { en: "/admin/scenario", fr: "/admin/scenario"}
    defaults: { _controller: KrakenAdminBundle:Scenario:list }

kraken_admin_scenario_tasks:
    locales:  { en: "/admin/scenario/{id}/tasks", fr: "/admin/scenario/{id}/taches"}
    defaults: { _controller: KrakenAdminBundle:Task:list }

kraken_admin_scenario_tasks_add_request:
    locales:  { en: "/admin/scenario/{id}/tasks/add/request", fr: "/admin/scenario/{id}/taches/ajout/requete"}
    defaults: { _controller: KrakenAdminBundle:Task:requestAdd }

kraken_admin_scenario_tasks_add:
    locales:  { en: "/admin/scenario/{id}/tasks/add/{type}", fr: "/admin/scenario/{id}/taches/ajout/{type}"}
    defaults: { _controller: KrakenAdminBundle:Task:add }

kraken_admin_scenario_tasks_edit:
    locales:  { en: "/admin/scenario/tasks/edit/{id}", fr: "/admin/scenario/taches/modification/{id}"}
    defaults: { _controller: KrakenAdminBundle:Task:edit }

kraken_admin_scenario_tasks_delete:
    locales:  { en: "/admin/scenario/tasks/delete/{id}", fr: "/admin/scenario/taches/suppression/{id}"}
    defaults: { _controller: KrakenAdminBundle:Task:delete }

kraken_admin_scenario_tasks_move:
    locales:  { en: "/admin/scenario/tasks/move/{id}/{position}", fr: "/admin/scenario/taches/deplacement/{id}/{position}"}
    defaults: { _controller: KrakenAdminBundle:Task:move }

kraken_admin_scenario_tasks_execute:
    locales:  { en: "/admin/scenario/tasks/execute/{id}", fr: "/admin/scenario/taches/execution/{id}"}
    defaults: { _controller: KrakenAdminBundle:Task:execute }

kraken_admin_scenario_tasks_social:
    locales:  { en: "/admin/scenario/tasks/social/{id}",  fr: "/admin/scenario/taches/social/{id}"}
    defaults: { _controller: KrakenAdminBundle:Task:social }

kraken_admin_scenario_tasks_social_callback:
    locales:  { en: "/admin/scenario/tasks/social/callback/{id}",  fr: "/admin/scenario/taches/social/callback/{id}"}
    defaults: { _controller: KrakenAdminBundle:Task:callbacksocial }

kraken_admin_scenario_tasks_input:
    locales:  { en: "/admin/scenario/tasks/input/{id}", fr: "/admin/scenario/taches/entrant/{id}"}
    defaults: { _controller: KrakenAdminBundle:Task:input }


kraken_admin_scenario_tasks_output:
    locales:  { en: "/admin/scenario/tasks/output/{id}", fr: "/admin/scenario/taches/sortant/{id}"}
    defaults: { _controller: KrakenAdminBundle:Task:output }

kraken_admin_scenario_add:
    locales:  { en: "/admin/scenario/add", fr: "/admin/scenario/ajout"}
    defaults: { _controller: KrakenAdminBundle:Scenario:add }

kraken_admin_scenario_edit:
    locales:  { en: "/admin/scenario/edit/{id}", fr: "/admin/scenario/modification/{id}"}
    defaults: { _controller: KrakenAdminBundle:Scenario:edit }

kraken_admin_scenario_delete:
    locales:  { en: "/admin/scenario/delete/{id}", fr: "/admin/scenario/suppression/{id}"}
    defaults: { _controller: KrakenAdminBundle:Scenario:delete }

kraken_admin_scenario_activate:
    locales:  { en: "/admin/scenario/activate/{id}", fr: "/admin/scenario/activation/{id}"}
    defaults: { _controller: KrakenAdminBundle:Scenario:activate }

kraken_admin_scenario_desactivate:
    locales:  { en: "/admin/scenario/desactivate/{id}", fr: "/admin/scenario/desactivation/{id}"}
    defaults: { _controller: KrakenAdminBundle:Scenario:desactivate }

#Users

kraken_admin_users:
    locales:  { en: "/admin/users", fr: "/admin/utilisateurs"}
    defaults: { _controller: KrakenAdminBundle:User:list }