parameters:
#    kraken_admin.example.class: Kraken\AdminBundle\Example

services:
#    kraken_admin.example:
#        class: %kraken_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
