parameters:
#    kraken_user.example.class: Kraken\UserBundle\Example

services:
#    kraken_user.example:
#        class: %kraken_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
