parameters:
#    kraken_core.example.class: Kraken\CoreBundle\Example

services:
#    kraken_core.example:
#        class: %kraken_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
